# Generated by Django 3.2.1 on 2021-11-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(upload_to='user/static/user/image'),
        ),
    ]
