# Generated by Django 3.2.1 on 2021-11-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_categorys_choose_employee_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='cart',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='choose',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
