# Generated by Django 3.2.1 on 2021-11-02 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20211102_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choose',
            unique_together={('user', 'order_date')},
        ),
    ]
