# Generated by Django 3.2.1 on 2021-11-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employee_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
