# Generated by Django 3.2.1 on 2021-11-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_employee_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=None),
        ),
    ]
