# Generated by Django 3.2.1 on 2021-11-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose',
            name='address',
            field=models.TextField(blank=True, default=None),
        ),
    ]
