# Generated by Django 3.2.1 on 2021-11-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211109_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
    ]
