# Generated by Django 3.2.1 on 2021-11-02 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_alter_choose_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choose',
            unique_together={('user', 'emp_id')},
        ),
    ]
