# Generated by Django 3.2.1 on 2021-11-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_choose_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
