# Generated by Django 3.2.1 on 2021-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_choose_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='choose',
            unique_together=set(),
        ),
    ]
