# Generated by Django 3.2.1 on 2021-11-11 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_choose_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
